// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTjBNxlm5_B20NEDVfI8SweKh8t-BhcVQ',
    appId: '1:281305728792:web:36a50a198f33f80099006d',
    messagingSenderId: '281305728792',
    projectId: 'assignment-9b7ad',
    authDomain: 'assignment-9b7ad.firebaseapp.com',
    storageBucket: 'assignment-9b7ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUy5jNbjNHjhWAjAEVbM2IMwd6RyUp5XI',
    appId: '1:281305728792:android:4179a1d6f5d8b55399006d',
    messagingSenderId: '281305728792',
    projectId: 'assignment-9b7ad',
    storageBucket: 'assignment-9b7ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8OXKqqOkZTPOk_KU3S6ETMCtWpoZ1_64',
    appId: '1:281305728792:ios:232852b91b12264e99006d',
    messagingSenderId: '281305728792',
    projectId: 'assignment-9b7ad',
    storageBucket: 'assignment-9b7ad.appspot.com',
    iosBundleId: 'com.example.contactAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8OXKqqOkZTPOk_KU3S6ETMCtWpoZ1_64',
    appId: '1:281305728792:ios:e08151fafa4c166e99006d',
    messagingSenderId: '281305728792',
    projectId: 'assignment-9b7ad',
    storageBucket: 'assignment-9b7ad.appspot.com',
    iosBundleId: 'com.example.contactAssignment.RunnerTests',
  );
}
